name: adp_mobile_preview
homepage: https://github.com/Abbas1Hussein/adp_mobile_preview/#/
description: "A simple tool for previewing the mobile app on desktop as an emulator."
version: 0.0.1

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

#platforms:
#  android:
#  ios:
#  linux:
#  macos:
#  windows:

dependencies:
  flutter:
    sdk: flutter

  window_manager: ^0.3.7
  device_frame: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/ios-bar-white.png

  fonts:
    - family: appleicon
      fonts:
        - asset: assets/appleicon.ttf