name: adp_mobile_preview
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  window_manager: ^0.3.7
  device_frame: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/ios-bar-white.png

  fonts:
    - family: appleicon
      fonts:
        - asset: assets/appleicon.ttf